on:
  workflow_dispatch:
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Check if a file exists
        run: |
          if [ -f "cocnfig.yaml"]; then
            echo "File exists"
          else
            echo "::error::config.yaml does not exist"
          fi
