on:
  workflow_dispatch:
jobs:
  expressions:
    steps:
      - name: Print a message
        run: echo "The job is running"
        if: ${{github.event_name == "push" || github.ref == "refs/heads/main"}}
