on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC

jobs:
  daily-task:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "This is a scheduled workflow running daily!"
